### ISSUE TITLE
Deduplicatte Rasmus in 2014

### ISSUE THREAD

**Issue by Philosoft** [phptodayorg/php-must-watch#10]
This two talks are practiclly identical (same slides, same topicas, sometimes excatly the same wording)

```
PHP 5.5 - Rasmus Lerdorf at phpDay 2014 [47:35]
PHPCraft SouthAfrica Keynote 2014 - Rasmus Lerdorf [1:00:43] 
```

First one is shorter, second has clearer sound. I suggest to get rid of one of these

**Comment by shameerc** [comment]
Hi @Philosoft,
Thanks for pointing that out. I'll remove the shorter one :)
