### ISSUE TITLE
Video link does not work

### ISSUE THREAD

**Issue by MichalGallovic** [phptodayorg/php-must-watch#17]
Hey guys, link to  *It Was Like That When I Got Here: Steps Toward Modernizing a Legacy Codebase - Paul M. Jones at Nashville* does not work. I tried googling it, but with no success so far.

**Comment by SpartakusMd** [comment]
@MichalGallovic Isn't it this one https://www.youtube.com/watch?v=65NrzJ_5j58 ?

**Comment by shameerc** [comment]
Thanks for reporting. I have fixed it.

**Comment by MichalGallovic** [comment]
Thank you guys 👍
